version: '3.7'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports: 
      - '8080:80'
    depends_on:
      - node
    networks:
      - network
  
  node:
    build:
      context: ./node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./start.sh
    volumes:
      - ./node:/app
    depends_on:
      - db
    networks:
      - network

  db:
    build: 
      context: ./mysql
    container_name: db
    restart: always
    tty: true
    networks:
      - network
    volumes:
      - ./mysql/volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

networks:
  network:
    driver: bridge